config/routes.rb
Rails.application.routes.draw do
  resources :student_infos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student_info.rb
class StudentInfo < ApplicationRecord
    enum :geneder, { male: 1, female: 2 }
    enum :matrial_status, { married: 1, single: 2, divorced: 3, widowed: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/student_infos_controller.rb
class StudentInfosController < ApplicationController
  before_action :set_student_info, only: %i[ show edit update destroy ]

  # GET /student_infos or /student_infos.json
  def index
    @student_infos = StudentInfo.all
  end

  # GET /student_infos/1 or /student_infos/1.json
  def show
  end

  # GET /student_infos/new
  def new
    @student_info = StudentInfo.new
  end

  # GET /student_infos/1/edit
  def edit
  end

  # POST /student_infos or /student_infos.json
  def create
    @student_info = StudentInfo.new(student_info_params)

    respond_to do |format|
      if @student_info.save
        format.html { redirect_to student_info_url(@student_info), notice: "Student info was successfully created." }
        format.json { render :show, status: :created, location: @student_info }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_infos/1 or /student_infos/1.json
  def update
    respond_to do |format|
      if @student_info.update(student_info_params)
        format.html { redirect_to student_info_url(@student_info), notice: "Student info was successfully updated." }
        format.json { render :show, status: :ok, location: @student_info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_infos/1 or /student_infos/1.json
  def destroy
    @student_info.destroy

    respond_to do |format|
      format.html { redirect_to student_infos_url, notice: "Student info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_info
      @student_info = StudentInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_info_params
      params.require(:student_info).permit(:first_name, :last_name, :age, :address, :geneder, :occuption, :matrial_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_infos_helper.rb
module StudentInfosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaherForms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/student_infos/_form.html.erb
<%= form_with(model: student_info) do |form| %>
  <div class="card">
    <div class="card-body">
      <% if student_info.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(student_info.errors.count, "error") %> prohibited this student_info from being saved:</h2>

          <ul>
            <% student_info.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3 row">
        <%= form.label :first_name, style: "display: block", class: 'col-sm-2 col-form-label' %>
        <%= form.text_field :first_name, class: 'col-sm-10 form-control', placeholder: 'First Name' %>
      </div>

      <div class="mb-3">
        <%= form.label :last_name, style: "display: block", class: 'form-label' %>
        <%= form.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
      </div>

      <div class="mb-3">
        <%= form.label :age, style: "display: block", class: 'form-label' %>
        <%= form.text_field :age, class: 'form-control', placeholder: 'Age' %>
      </div>

      <div class="mb-3">
        <%= form.label :address, style: "display: block", class: 'form-label' %>
        <%= form.text_field :address, class: 'form-control', placeholder: 'Address' %>
      </div>

      <div class="mb-3">
        <%= form.label :geneder, style: "display: block", class: 'form-label' %>
        <%= form.select :geneder , StudentInfo.geneders.keys, class: 'form-select'%>
      </div>

      <div class="mb-3">
        <%= form.label :occuption, style: "display: block", class: 'form-label' %>
        <%= form.text_field :occuption, class: 'form-control', placeholder: 'Occuption' %>
      </div>

      <div class="mb-3">
        <%= form.label :martial_status, style: "display: block", class: 'form-label' %>
        <%= form.select :matrial_status, StudentInfo.matrial_statuses.keys, class: 'form-select'%>
      </div>

      <div class="mb-3">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/student_infos/_student_info.html.erb
<div id="<%= dom_id student_info %>">
  <tr>
    <td><%= student_info.first_name %></td>
    <td><%= student_info.last_name %></td>
    <td><%= student_info.age %></td>
    <td><%= student_info.address %></td>
    <td><%= student_info.occuption %></td>
    <td><%= student_info.geneder %></td>
    <td><%= student_info.matrial_status %></td>
    <td><%= link_to "Show", student_info %></td>
  </tr
</div>

app/views/student_infos/edit.html.erb
<h1>Editing student info</h1>

<%= render "form", student_info: @student_info %>

<br>

<div>
  <%= link_to "Show this student info", @student_info %> |
  <%= link_to "Back to student infos", student_infos_path %>
</div>

app/views/student_infos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Student infos</h1>

<%= link_to "New student info", new_student_info_path %>


<div id="student_infos">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">First Name</th>
        <th scope="col">Age</th>
        <th scope="col">Address</th>
        <th scope="col">Geneder</th>
        <th scope="col">Occuption</th>
        <th scope="col">Matrial Status</th>
        <th scope="col">Show</th>
      </tr>
    </thead>
    <tbody>
      <% @student_infos.each do |student_info| %>
        <%= render student_info %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/student_infos/new.html.erb
<h1>New student info</h1>

<%= render "form", student_info: @student_info %>

<br>

<div>
  <%= link_to "Back to student infos", student_infos_path %>
</div>

app/views/student_infos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student_info %>

<div>
  <%= link_to "Edit this student info", edit_student_info_path(@student_info) %> |
  <%= link_to "Back to student infos", student_infos_path %>

  <%= button_to "Destroy this student info", @student_info, method: :delete %>
</div>